version: '3.1'

services:
  core:
    image: openjdk:21-jdk-slim-buster
    container_name: core
    command: java -jar /core.jar
    volumes:
      - "./core/target/core-0.0.1-SNAPSHOT.jar:/core.jar"
    ports:
      - "8080:8080"
  mail:
    image: openjdk:21-jdk-slim-buster
    container_name: mail
    command: java -jar /mail.jar
    volumes:
      - "./mail/target/core-0.0.1-SNAPSHOT.jar:/mail.jar"
    ports:
      - "8081:8081"
  postgres:
    image: postgres:latest
    container_name: postgres
    command: [ "postgres", "-c", "fsync=off", "-c", "full_page_writes=off" ]
    environment:
      POSTGRES_DB: denis
      POSTGRES_USER: denis
      POSTGRES_PASSWORD: denis
    ports:
      - "5432:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper